sort-string
js-tasks-ru/js-20230223_black-s-w-a-n pull request #2
Opened 2023-02-27 20:59 UTC by DovgiyA

2023-02-27 21:00 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-01 09:06 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return newArr.sort((a, b) => a.localeCompare(b, 'ru', { caseFirst: 'upper' }));
пожалуйста устраните дубликаты кода, 
строка 10 дублирует строку 13

2023-03-01 09:06 UTC, dosandk requested changes
пожалуйста внесите правки

2023-03-01 18:33 UTC, DovgiyA commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return newArr.sort((a, b) => a.localeCompare(b, 'ru', { caseFirst: 'upper' }));
Строка 10 не совсем дублирует 13, так как на 10 строке a.localeCompare(b), а на 13 b.localeCompare(a) для реализации сортировки в обратном порядке. Или я что-то неправильно понял?

2023-03-01 18:35 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-01 18:58 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-01 19:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-01 19:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-03-02 12:19 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return newArr.sort((a, b) => a.localeCompare(b, 'ru', { caseFirst: 'upper' }));
так все остальное, кроме порядка аргументов - это дубликаты
вынесите в ф-цию, и передавайте значения в нужном порядке
```js
const compare = (a, b) => {
  newArr.sort((a, b) => a.localeCompare(b, 'ru', { caseFirst: 'upper' }));
}

compare(first, second);
compare(second, first);
```

2023-03-02 12:19 UTC, dosandk approved these changes
👍 good

2023-03-02 12:20 UTC, merged